### ISSUE TITLE
bug: shoving searchPrefix in SearchTextField

### ISSUE THREAD

**Issue by Hanna922** [yourssu/YDS-React#102]
# ISSUE ✅ : shoving searchPrefix in SearchTextField

## 📖 Summary

SearchTextField focus 시 searchPrefix icon이 밀리는 현상 발생ㅠ
=> 아이콘이 작아졌다 커졌다 합니다..

**Comment by nijuy** [comment]
아 오케 먼말알
이거 걍 suffix처럼 컴포넌트 하나 만들어서 감싸면 안 움직이긴 하는데........
해결책말고 왜 이러는지가................................... 잘 몰으겠어서 쫌만 더 쳐다볼게욧

**Comment by nijuy** [comment]
아님 suffix (x 버튼) 제어를 display 말고 원래처럼 visibility로 해도 안 움직여요!!!!

**Comment by Hanna922** [comment]
visibility가 간결하니까 visibility로 가시죠
근데 얘 아이콘 크기 수정이랑 필요없는 코드도 있어서 한 번에 싹 다 올릴게요

**Comment by nijuy** [comment]
네엥

**Comment by Hanna922** [comment]
에엥 얘 근데 visibility로 하니까 아이콘 가로 세로 크기가 달라지는 이슈가 발생해요
display로 제어하고 div로 감싸서 영역을 딱 지정해줘야 할 것 같은 고런 느낌

### 기존 코드
<img width="299" alt="image" src="https://github.com/yourssu/YDS-React/assets/84809236/8eaa95f5-8f44-43fd-b8f6-144725f96915">

**Comment by nijuy** [comment]
아항. 어디서 봤다 했는데 그거 visibilty 때문 아니에요 (display 일 때도 가로 길이 보장 안됨)

![image](https://github.com/yourssu/YDS-React/assets/87255462/c82305a3-2b59-4407-8582-42bd0545e0cf)

**Comment by Hanna922** [comment]
div로 감싸고 visibility로 해도 되긴 하는데, 어쨌든 div로 감싸는 거면 뭐든 상관없을 것 같네요 ㅋㅋ큐ㅠ
