### ISSUE TITLE
bug: searchPrefix가 없을 때도 StyledSearchPrefixContainer가 렌더링 되는 문제

### ISSUE THREAD

**Issue by nijuy** [yourssu/YDS-React#104]
# ISSUE ✅ :

## 📖 Summary

![image](https://github.com/yourssu/YDS-React/assets/87255462/e6272b0a-5762-48c2-9816-3a246c1bc546)

## Error Script

searchPrefix prop이 없을 때 (SimpleTextField 같은) div가 잡혀서 약간.. 여백이 생김

**Comment by Hanna922** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
