### ISSUE TITLE
IcShareLine 삼각형이 채워져있는 문제

### ISSUE THREAD

**Issue by nijuy** [yourssu/YDS-React#36]
- 문제 상황
  ![image](https://github.com/yourssu/YDS-React/assets/87255462/775f3d75-2fc6-40c7-8f07-117362adcad4)

  https://github.com/yourssu/Soomsil-Web/pull/32 에서 발견한 이슈

<br/>

- 원인

  ```html
  // 현재 ic_share_line.svg
  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  // 원 3개
  <path fill-rule="evenodd" clip-rule="evenodd" d="M20 5C20 6.65685 18.6569 8 17 8C15.3431 8 14 6.65685 14 5C14 3.34315 15.3431 2 17 2C18.6569 2 20 3.34315 20 5ZM10 12C10 13.6569 8.65685 15 7 15C5.34315 15 4 13.6569 4 12C4 10.3431 5.34315 9 7 9C8.65685 9 10 10.3431 10 12ZM17 22C18.6569 22 20 20.6569 20 19C20 17.3431 18.6569 16 17 16C15.3431 16 14 17.3431 14 19C14 20.6569 15.3431 22 17 22Z" />
  // < 선
  <path d="M17 5L7 12L17 19" stroke="current" stroke-width="1.5"/>
  </svg>
  ```
  
  `svg` 태그 `fill="none"` && `path` fill 지정 안됨 ➡ 삼각형이 안 채워지는 게 맞긴 함 **`.svg` 파일만 보면**

  근데 `IconBase` 보면 `fill`에 사용자가 지정한 색을 넣기 때문에 결국 svg 태그 `fill` 값이 존재하는 셈 (이래서 삼각형이 채워진다)
  ```html
      // IconBase = .svg -> .tsx 과정에서 사용되는 컴포넌트. svg 역할을 함
      <svg
        .....
        fill={color ?? contextColor}
      >
        {children}
      </svg>
  ```

- 뭔가시도해보는중
  
  목표: ic_share_line에서 svg fill이 존재할 때 path는 fill 하지 않아야 함
  
  1. svg에서 path의 fill:none ➡ 소용 없음 `convert.mjs` 거치면서 `fill` 속성 삭제됨

  2. `convert.mjs`를 건드린다 ➡ 걍 딱봐도 기각 다른 아이콘에서 뭔 일이 생길 줄 알고 이걸 건드림? 절대안됨
  그리고 path의 fill 속성은 삭제하는 게 맞다 (피그마에서 export 하면서 지정된 컬러 삭제하는 과정이라)

  3. IcShareLine.tsx를 직접 수정 ➡️ 일단 근본적인 해결이 아님... convert.mjs 한번 돌리면 다시 문제가 발생하므로 백퍼 언젠가 한번 터질듯 기각

  4. path 말고 다른 거 쓴다 ➡️ 애초에 path가 fill에 영향 받는 엘리먼트라서 문제가 생긴거니까 이걸 바꾸면? 안되나?

    path로 그리고 있는 선이 복잡한 구조가 아님 직선 2개라서 fill에 영향 받지 않는 line 2개로 바꿔도 될

    거라고 생각했는데 안됨;;;; stroke 색상을 svg(IconBase)에서 상속 받아야 하는데, IconBase에 stroke 속성을 넣으면 다른 아이콘들이 불필요한 stroke width 때문에 두꺼워짐

**Comment by nijuy** [comment]
line은 stroke로 색 입혀야해서 안됨
그럼 fill로 색 입히는 엘리먼트 중에서 직선을 표현할 수 있어야 하는데

Rect 높이 1로 하면 걍 선 아닌가???
원이랑 위치 조절만 수작업으로,,....,........ 해서 해보기 


+) 핸드폰으로 여기까진 함 될거같음
![image](https://github.com/yourssu/YDS-React/assets/87255462/77919e1c-20e6-4972-ab73-3f22ff185af1)

**Comment by nijuy** [comment]
각도랑 길이 약간 조절해서 100%는 아닌디......... 이정도까진 맞춰둠

![image](https://github.com/yourssu/YDS-React/assets/87255462/418e0590-3003-46a7-88ad-3d518007fd2d)

**Comment by 2wndrhs** [comment]
![image](https://github.com/yourssu/YDS-React/assets/76615094/f6e93146-84ac-4241-9214-f0897c8add2d)

**Comment by nijuy** [comment]
> ![image](https://private-user-images.githubusercontent.com/76615094/306052882-f6e93146-84ac-4241-9214-f0897c8add2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNjk0ODcsIm5iZiI6MTcwODM2OTE4NywicGF0aCI6Ii83NjYxNTA5NC8zMDYwNTI4ODItZjZlOTMxNDYtODRhYy00MjQxLTkyMTQtZjA4OTdjOGFkZDJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDE4NTk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NmNmOTBjY2I4YmViMTAwNDZkOGU1NWI0ZGZkMWUwNzU3NWMzNjNmMjRlZmRkOWU0OGFkNDhlMGYxMTQwNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B8ur8u0Ru676nnl293H8z9zSmDn4CUcV-774uyLPeYg)

열렬한 반응 감사합니다 ^^~

**Comment by shon5544** [comment]
![image](https://github.com/yourssu/YDS-React/assets/65557784/89c79fe8-a982-4099-adcf-f9def6f8fe90)

**Comment by nijuy** [comment]
> ![image](https://private-user-images.githubusercontent.com/65557784/306053174-89c79fe8-a982-4099-adcf-f9def6f8fe90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNjk2MjIsIm5iZiI6MTcwODM2OTMyMiwicGF0aCI6Ii82NTU1Nzc4NC8zMDYwNTMxNzQtODljNzlmZTgtYTk4Mi00MDk5LWFkY2YtZjlkZWY2ZjhmZTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDE5MDIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0YWFhNzcyNzk0ZTNkODRmYTM1YTczMWY4YjhiMzM4OGU2YzRmYzU1MGU2M2U5YmQ4MzMzZDA0NDFjYzA2NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._MBfoQFvfZwCwAMUjBHS2dYOrrCXJ6lEEgJmI6FDrB8)

환영합니다 종종 놀러오세요 ^^~

**Comment by Twince** [comment]
![당신최고야](https://github.com/yourssu/YDS-React/assets/55754148/44dfe6ac-8016-498a-8146-cb86db613a66)

**Comment by nijuy** [comment]
그만해주세요

**Comment by Hanna922** [comment]
![당신최고야](https://github.com/yourssu/YDS-React/assets/55754148/44dfe6ac-8016-498a-8146-cb86db613a66)
