### ISSUE TITLE
YDS `buttonDisabled` 색상 수정

### ISSUE THREAD

**Issue by 2wndrhs** [yourssu/YDS-React#40]
피그마
<img width="79" alt="image" src="https://github.com/yourssu/YDS-React/assets/76615094/aa2d780a-192b-4e1d-99f3-6f0749ab3718">

현재 YDS 코드
```
buttonDisabled: baseColorPalettes.light.gray600,
```
↓
```
buttonDisabled: baseColorPalettes.light.gray500,
```
로 수정 부탁드려요🙏

**Comment by Hanna922** [comment]
제보 감사합니당~! 다음 버전 때 추가할게요~!

**Comment by 2wndrhs** [comment]
![image](https://github.com/yourssu/YDS-React/assets/76615094/32175ec9-3527-4424-a9e4-fb04a113f2f3)
