### ISSUE TITLE
bug: tsc error in Toast.stories.tsx

### ISSUE THREAD

**Issue by Hanna922** [yourssu/YDS-React#55]
# ISSUE ✅ : tsc error in Toast.stories.tsx

## 📖 Summary

tsc 시 Toast.stories.tsx Description에서 에러 터짐
=> children deprecated 된 걸로 보임

## Error Script

src/components/Toast/Toast.stories.tsx:38:12 - error TS2559: Type '{ children: string; }' has no properties in common with type 'IntrinsicAttributes & DescriptionProps'.

38           <Description>Toast 컴포넌트를 사용하기 위한 Custom Hook입니다.</Description>
              ~~~~~~~~~~~

Found 1 error in src/components/Toast/Toast.stories.tsx:38

 ELIFECYCLE  Command failed with exit code 2.

## Photo

<img width="814" alt="image" src="https://github.com/yourssu/YDS-React/assets/84809236/22017540-b1ab-4948-9e2c-c7bfc8b89511">

**Comment by EATSTEAK** [comment]
[참고](https://storybook.js.org/docs/api/doc-block-description)

`<Description>` 사용 방법이 바뀌었네요. `parameters.docs.description.component` 프로퍼티로 Description 내부 내용을 채운 다음 `of`를 써서 참조하는 걸로 우선 해결하고, 점진적으론 JSDoc 활용하여 스토리북 생성을 하는 방향은 어떨까요?

**Comment by Hanna922** [comment]
>parameters.docs.description.component 프로퍼티로 Description 내부 내용을 채운 다음 of를 써서 참조하는 걸로 우선 해결

오 좋네요!! 참고 레퍼런스 감사합니다👍🏻
@nijuy PR에 방법 두 가지를 여쭤봤었는데, 이 방법이 더 좋은 것 같아서 이렇게 작업할게요~!

**Comment by Hanna922** [comment]
> `of`를 써서 참조하는 걸로 우선 해결하고

이 부분 참조를 사용하려면 .mdx 파일 내에서 사용해야 하는 것 같은데, 저희가 스토리북 문서를 자동 생성하고 있어서 작성하는 데 조금 어려움이 존재하네용
현재 Toast 문서에 Description이 필수적인 요소가 아니라서 span으로 해결해도 충분히 문제가 없을 것 같습니다!
