### ISSUE TITLE
refactor: 웹에 맞게 Toast.style 수정

### ISSUE THREAD

**Issue by nijuy** [yourssu/YDS-React#79]
# ISSUE ✅ : REFACTOR

## 📖 Summary

현재 토스트는 모바일 화면을 보고 만들어서 실제로 웹에서 사용했을 때 문제가 많음

## TODO
- [x] 위치 기준 변경 (전체 화면 -> 현재 화면)

  전체 화면으로 기준을 잡으면 스크롤이 생기는 페이지에서는 스크롤 내려야 토스트 확인 가능한 문제가 있음

- [x] width props 추가

  현재는 Toast를 감싸는 부모 컴포넌트의 너비를 가져와서 사용하는데, 웹에서는 과하게 길어지는 문제가 있음
  차라리 사용자한테 입력 가능하게 해주는 게 나을듯?

**Comment by Hanna922** [comment]
Toast.style.ts 보면 빨간 줄 뜨고 있는데, 요것도 같이 수정하면 좋을 것 같네요

<img width="746" alt="image" src="https://github.com/yourssu/YDS-React/assets/84809236/fde6a26e-77a6-49e5-813a-35f39d2ea4ad">

**Comment by nijuy** [comment]
저거 마유ㅜ스 올리면 내용 뭐라 떠요?? 저한텐 안 떠서 뭔지 확인 할 수가 ❌

![image](https://github.com/yourssu/YDS-React/assets/87255462/9ac7cdac-a13f-418d-92ff-678631a34563)

**Comment by Hanna922** [comment]
ts-styled-plugin 이라고 뜨는데, 보리 혹시 vscode-styled-components 익스텐션 사용 안 하시나요?? 익스텐션 제거하니까 전부 문자열로 떠서용

<img width="851" alt="image" src="https://github.com/yourssu/YDS-React/assets/84809236/13baeedf-67dd-4e5a-9c09-9fd942e75b97">

**Comment by Hanna922** [comment]
보리 혹시 vscode-styled-components 확장 안 깔려 있으신가요?

**Comment by nijuy** [comment]
넹 전 그거 안 써서 안 떴나봐여!

**Comment by Hanna922** [comment]
옹 이 확장 없으면 styled-components 자동완성 안 되지 않나요??
이거 쓰면 자동완성이랑 하이라이팅 전부 해줘서,,, ([Reference](https://velog.io/@heumheum2/vscode%EC%97%90-styled-component-%EB%AC%B8%EB%B2%95-%ED%95%98%EC%9D%B4%EB%9D%BC%EC%9D%B4%ED%8C%85-%ED%95%98%EA%B8%B0))
확장 추천으로 vscode-styled-components 뜨게끔 코드 설정하고, 이 코드도 수정하면 좋을 것 같아요

=> recommendations 추가한 PR 올려둘게용

**Comment by nijuy** [comment]
네~~
