### ISSUE TITLE
feat: create ProfileImageView

### ISSUE THREAD

**Issue by Hanna922** [yourssu/YDS-React#83]
# ISSUE ✅ : create ProfileImageView

## 📖 Summary

ProfileImageView 구현해두기

<img width="612" alt="image" src="https://github.com/yourssu/YDS-React/assets/84809236/33e2a38f-2a76-42c2-83be-c549be9b864f">

**Comment by nijuy** [comment]
handy로 개편하면서 profileimageview 컴포넌트가 사라져서 이슈 닫습니다~!
